### ISSUE TITLE
Conflict with Questplates progress addon.

### ISSUE THREAD

**Issue by Gizmojo** [ImogenBits/tidyplates#10]
I am getting a conflict when running Tidyplates and Questplates together. These worked together in BFA , but now I get double name plates and questplates' quest progress does not display. Both addons have been updated for 9.0 pre-patch.

I have tried other plate addons, and Questplates works as expected with: Kui Name Plates, Plater, Threat Plates Simple, or without any plate addon at all active. 

It does not work with Neat Plates or Tidyplates. However, Tidyplates is the only addon that displays the double nameplates with Questplates.

Can you help?

**Comment by ImogenBits** [comment]
Gonna need look into this further. So far I thought this was an issue with QuestPlates not having an update for 9.0.1 yet. I'll try to find a solution to make them work together again, but so far I have absolutely no idea what is causing it or how QuestPlates works so that might take a while.
Unfortunately the best I can say right now is to disable either of our addons.

**Comment by ImogenBits** [comment]
Ended up being much faster than I thought. Is fixed and will be released with the next update.

**Comment by Gizmojo** [comment]
Indeed, it IS fixed in the recent update.

Thank you, THANK you, THANK YOU!
