### ISSUE TITLE
Default Blizzard nameplates appearing under Tidyplates nameplate

### ISSUE THREAD

**Issue by scorpgul** [ImogenBits/tidyplates#17]
Hi I reported this issue last week but the thread was closed for some reason. This is still happening. The previous version fixed it but in this version this is still happening. Initially I was noticing it mainly as warrior. I can now confirm it happens on all classes. I have larger nameplates enabled under Blizzard settings. No other addons are enabled that could be causing this.

This is the issue that is still happening after the latest update:

https://github.com/Binbwen/tidyplates/issues/63#issuecomment-714910803

**Comment by ImogenBits** [comment]
I closed the issue because I found a fix that works on my system, but I have a feeling that it breaks other things that I just haven't found yet. As far as I can tell it's also not an issue that regularly happens in combat, usually only for a few frames and only in very specific situations. As such I need more time to test it before I'm comfortable releasing a patch that has the potential to completely break the addon for many others.
Yes, it's annoying for you now and I'm sorry about that. But I hope you can understand why I need a bit more patience before I release the fix.

**Comment by scorpgul** [comment]
Thank you for your reply and do not worry I understand why you are delaying the fix. As you mentioned, its not too severe so I can put up with it until SL releases. Thank you for the work you are doing masintaining this crucial addon!
