### ISSUE TITLE
Blizzard Health Bar is Showing.

### ISSUE THREAD

**Issue by sirdangles** [ImogenBits/tidyplates#3]
When I have TidyPlates enabled, I still see the Blizzard health bar under the TidyPlates health bar.  I've tried turning off enemy names, but that removes both health bars.  Is there a setting I need to change?

**Comment by ImogenBits** [comment]
Do you have the addon QuestPlates installed? If so that is a known issue that I currently believe to be on their side, so I can't really fix it.
There also was a similar issue that I thought I fixed with version 6.19.6 please make sure your install is up to date with that version.

If neither of those cases apply, can you please give me a more detailed description? I can tell you that it's most likely not an issue with your settings, but not much more than that. Have you taken any game actions that lead to this problem? Do they always show or just for short amounts of time? Do they show on all units r just specific ones? A screenshot of it happening would also be helpful.
I want to fix bugs like these, but I need to be able to reproduce them myself first so anything that helps with that is greatly appreciated.

**Comment by sirdangles** [comment]
Thank you for the fast reply.  I do have Quest Plates installed, and disabling it seemed to fix the issue. Thank you very much!
