### ISSUE TITLE
only cc debuffs

### ISSUE THREAD

**Issue by AenacSky** [ImogenBits/tidyplates#67]
Hey, can you set an option, where it says, that only ALL CC's will show over healthbar? dont need buffs or debuffs, just CC like sheep, blind etc. and all players in group, not just mine. THANK YOU :)

**Comment by ImogenBits** [comment]
I was looking into that a while ago and I couldn't find a way to get the info on what is CC and what isn't from the blizzard api, so I can't do it automatically. my solution was to just add the to the spell filter so that only those get shown. this is the list that i have now, but this certainly doesn't cover all CC that exists in the game and probably also has some other stuff on it that I want to see for other reasons, so you probably wanna change it as you see fit for yourself:
```
Charge
Soul Fetish
Minor Swiftness Ward
Leg Sweep
163505
Hammer of Justice
Thunderstruck
Steel Trap
Hibernate
Swiftness Ward
Blind
Fel Eruption
Warpath
Psychic Scream
Psychic Horror
Freezing Trap
Shackle Undead
Censure
Mind Bomb
Fear
Hex
Kidney Shot
Storm Bolt
Pulverize
Maim
Intimidation
Sap
118905
Cheap Shot
Shockwave
Dragon's Breath
Blinding Light
Axe Toss
Entangling Roots
Incapacitating Roar
Banish
Quaking Palm
Seduction
Provoke
Gnaw
Holy Word: Chastise
Sigil of Misery
Shadowfury
Charged Claw
Swiftness
Chaos Nova
Asphyxiate
Ancestral Fury
Ferocity
Sundering
Intimidating Shout
Mass Entanglement
Between the Eyes
Mortal Coil
Imprison
Binding Sleet
Polymorph
Ring of Frost
Gouge
Summon Infernal
Monstrous Blow
Mighty Bash
Paralysis
Song of Chi-Ji
Repentance
```
